.TH "ConstructedMaterial::Field" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstructedMaterial::Field \- Holds data for \fBField\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ConstructedMaterial\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBkey\fP"
.br
.ti -1c
.RI "std::string \fBdisplayName\fP"
.br
.ti -1c
.RI "std::string \fBuniformName\fP"
.br
.ti -1c
.RI "std::string \fBmirrorUniformName\fP"
.br
.ti -1c
.RI "std::string \fBpresenceUniformName\fP"
.br
.ti -1c
.RI "\fBFieldType\fP \fBtype\fP = FieldType::Float"
.br
.ti -1c
.RI "float \fBfloatValue\fP = 0\&.0f"
.br
.ti -1c
.RI "int \fBintValue\fP = 0"
.br
.ti -1c
.RI "bool \fBboolValue\fP = false"
.br
.ti -1c
.RI "Math3D::Vec2 \fBvec2Value\fP = Math3D::Vec2(0\&.0f, 0\&.0f)"
.br
.ti -1c
.RI "Math3D::Vec3 \fBvec3Value\fP = Math3D::Vec3(0\&.0f, 0\&.0f, 0\&.0f)"
.br
.ti -1c
.RI "Math3D::Vec4 \fBvec4Value\fP = Math3D::Vec4(0\&.0f, 0\&.0f, 0\&.0f, 1\&.0f)"
.br
.ti -1c
.RI "std::string \fBtextureAssetRef\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTexture\fP > \fBtexturePtr\fP"
.br
.ti -1c
.RI "std::string \fBloadedTextureRef\fP"
.br
.ti -1c
.RI "int \fBtextureSlot\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBField\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
