.TH "src/Rendering/Materials/ConstructedMaterial.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/ConstructedMaterial.cpp \- Implementation for \fBConstructedMaterial\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Materials/ConstructedMaterial\&.h'\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br
\fR#include 'Rendering/Materials/PBRMaterial\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include <utility>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBConstructedMaterial\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
