.TH "src/Rendering/Materials/ConstructedMaterial.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/ConstructedMaterial.h \- Declarations for \fBConstructedMaterial\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstructedMaterial\fP"
.br
.RI "Represents the \fBConstructedMaterial\fP type\&. "
.ti -1c
.RI "struct \fBConstructedMaterial::Field\fP"
.br
.RI "Holds data for \fBField\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBConstructedMaterial\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
