.TH "src/Rendering/Lighting/Environment.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/Environment.h \- Declarations for \fBEnvironment\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnvironment\fP"
.br
.RI "Represents the \fBEnvironment\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBSkyBox\fP > \fBPSkyBox\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBEnvironment\fP > \fBPEnvironment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBEnvironment\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
