.TH "FontCharacter" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontCharacter \- Holds data for \fBFontCharacter\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBu0\fP"
.br
.ti -1c
.RI "float \fBv0\fP"
.br
.ti -1c
.RI "float \fBu1\fP"
.br
.ti -1c
.RI "float \fBv1\fP"
.br
.ti -1c
.RI "float \fBsizeX\fP"
.br
.ti -1c
.RI "float \fBsizeY\fP"
.br
.ti -1c
.RI "float \fBbearingX\fP"
.br
.ti -1c
.RI "float \fBbearingY\fP"
.br
.ti -1c
.RI "float \fBadvance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBFontCharacter\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
