.TH "src/Rendering/Fonts/FreeTypeFont.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Fonts/FreeTypeFont.h \- Declarations for \fBFreeTypeFont\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <ft2build\&.h>\fP
.br
\fR#include 'Rendering/Fonts/Font\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFreeTypeFont\fP"
.br
.RI "Represents the \fBFreeTypeFont\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBFreeTypeFont\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
