.TH "src/Rendering/Fonts/FreeTypeFont.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Fonts/FreeTypeFont.cpp \- Implementation for \fBFreeTypeFont\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Fonts/FreeTypeFont\&.h'\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include <cmath>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBFreeTypeFont\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
