.TH "GLUniformUpload::CubeMapSlot" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLUniformUpload::CubeMapSlot \- Holds data for \fBCubeMapSlot\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ShaderProgram\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCubeMapSlot\fP ()=default"
.br
.RI "Constructs a new \fBCubeMapSlot\fP instance\&. "
.ti -1c
.RI "\fBCubeMapSlot\fP (std::shared_ptr< \fBCubeMap\fP > map, int s=0)"
.br
.RI "Constructs a new \fBCubeMapSlot\fP instance\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBCubeMap\fP > \fBcubemap\fP"
.br
.ti -1c
.RI "int \fBslot\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBCubeMapSlot\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLUniformUpload::CubeMapSlot::CubeMapSlot (std::shared_ptr< \fBCubeMap\fP > map, int s = \fR0\fP)\fR [inline]\fP"

.PP
Constructs a new \fBCubeMapSlot\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP Value for map\&. 
.br
\fIs\fP Value for s\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
