.TH "GLUniformUpload::TextureSlot" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLUniformUpload::TextureSlot \- Holds data for \fBTextureSlot\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ShaderProgram\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureSlot\fP ()=default"
.br
.RI "Constructs a new \fBTextureSlot\fP instance\&. "
.ti -1c
.RI "\fBTextureSlot\fP (std::shared_ptr< \fBTexture\fP > tex, int s=0)"
.br
.RI "Constructs a new \fBTextureSlot\fP instance\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBTexture\fP > \fBtexture\fP"
.br
.ti -1c
.RI "int \fBslot\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBTextureSlot\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLUniformUpload::TextureSlot::TextureSlot (std::shared_ptr< \fBTexture\fP > tex, int s = \fR0\fP)\fR [inline]\fP"

.PP
Constructs a new \fBTextureSlot\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fItex\fP Value for tex\&. 
.br
\fIs\fP Value for s\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
