.TH "Graphics::Image::BufferedImage" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graphics::Image::BufferedImage \- Holds data for \fBBufferedImage\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Graphics\&.h>\fP
.PP
Inherits \fBGraphics::Image::Image\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBufferedImage\fP (int width, int height)"
.br
.RI "Constructs a new \fBBufferedImage\fP instance\&. "
.ti -1c
.RI "\fBBufferedImage\fP (const \fBImage\fP &src)"
.br
.ti -1c
.RI "uint32_t \fBgetValueAt\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBsetValueAt\fP (int x, int y, uint32_t value)"
.br
.ti -1c
.RI "Color \fBgetPixelAt\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBsetPixelAt\fP (int x, int y, Color col)"
.br
.in -1c

Public Member Functions inherited from \fBGraphics::Image::Image\fP
.in +1c
.ti -1c
.RI "\fBImage\fP ()=delete"
.br
.RI "Constructs a new \fBImage\fP instance\&. "
.ti -1c
.RI "\fBImage\fP (int width, int height)"
.br
.RI "Constructs a new \fBImage\fP instance\&. "
.ti -1c
.RI "\fBImage\fP (const Image &src)"
.br
.RI "Constructs a new \fBImage\fP instance\&. "
.ti -1c
.RI "int \fBgetWidth\fP () const"
.br
.RI "Returns the width\&. "
.ti -1c
.RI "int \fBgetHeight\fP () const"
.br
.ti -1c
.RI "std::vector< uint32_t > \fBgetPixelData\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBGraphics::Image::Image\fP
.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBImage\fP > \fBCreate\fP (int width, int height, const std::vector< uint32_t > &src={})"
.br
.RI "Creates a new object\&. "
.in -1c

Public Attributes inherited from \fBGraphics::Image::Image\fP
.in +1c
.ti -1c
.RI "std::vector< uint32_t > \fBpixelData\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBBufferedImage\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Graphics::Image::BufferedImage::BufferedImage (int width, int height)\fR [inline]\fP"

.PP
Constructs a new \fBBufferedImage\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP Dimension value\&. 
.br
\fIheight\fP Dimension value\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Graphics::Image::BufferedImage::setValueAt (int x, int y, uint32_t value)\fR [inline]\fP"
MAX RGBA value

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
