.TH "src/Rendering/Core/Graphics2D.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/Graphics2D.h \- Declarations for \fBGraphics2D\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Core/Screen\&.h'\fP
.br
\fR#include 'Scene/Camera\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include 'Rendering/Geometry/ModelPartPrefabs\&.h'\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'Foundation/Util/ValueContainer\&.h'\fP
.br
\fR#include 'Foundation/Math/Color\&.h'\fP
.br
\fR#include 'Rendering/Fonts/Font\&.h'\fP
.br
\fR#include 'Rendering/Fonts/FreeTypeFont\&.h'\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGraphicsContext\fP"
.br
.RI "Holds data for \fBGraphicsContext\fP\&. "
.ti -1c
.RI "class \fBGraphics2D\fP"
.br
.RI "Represents the \fBGraphics2D\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBGraphics2D\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
