.TH "src/Rendering/Core/Graphics2D.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/Graphics2D.cpp \- Implementation for \fBGraphics2D\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Core/Graphics2D\&.h'\fP
.br
\fR#include <algorithm>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBGraphics2D\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
