.TH "GrayscaleEffect" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GrayscaleEffect \- Represents the \fBGrayscaleEffect\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ScreenEffects\&.h>\fP
.PP
Inherits \fBGraphics::PostProcessing::PostProcessingEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrayscaleEffect\fP ()"
.br
.RI "Constructs a new \fBGrayscaleEffect\fP instance\&. "
.ti -1c
.RI "bool \fBapply\fP (PTexture tex, PTexture depthTex, PFrameBuffer outFbo, std::shared_ptr< \fBModelPart\fP > quad) override"
.br
.RI "Applies current settings\&. "
.in -1c

Public Member Functions inherited from \fBGraphics::PostProcessing::PostProcessingEffect\fP
.in +1c
.ti -1c
.RI "virtual \fB~PostProcessingEffect\fP ()=default"
.br
.RI "Destroys this \fBPostProcessingEffect\fP instance\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Graphics::PostProcessing::PPostProcessingEffect \fBNew\fP ()"
.br
.RI "Creates a new object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the \fBGrayscaleEffect\fP type\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool GrayscaleEffect::apply (PTexture tex, PTexture depthTex, PFrameBuffer outFbo, std::shared_ptr< \fBModelPart\fP > quad)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Applies current settings\&. 
.PP
\fBParameters\fP
.RS 4
\fItex\fP Value for tex\&. 
.br
\fIdepthTex\fP Value for depth tex\&. 
.br
\fIoutFbo\fP Output value for fbo\&. 
.br
\fIquad\fP Value for quad\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True when the operation succeeds; otherwise false\&. 
.RE
.PP

.PP
Implements \fBGraphics::PostProcessing::PostProcessingEffect\fP\&.
.SS "Graphics::PostProcessing::PPostProcessingEffect GrayscaleEffect::New ()\fR [inline]\fP, \fR [static]\fP"

.PP
Creates a new object\&. 
.PP
\fBReturns\fP
.RS 4
Result of this operation\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
