.TH "src/Rendering/Lighting/Light.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/Light.cpp \- Implementation for \fBLight\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBLight\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
