.TH "src/Rendering/Lighting/LightUtils.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/LightUtils.cpp \- Implementation for LightUtils\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Lighting/LightUtils\&.h'\fP
.br
\fR#include <glad/glad\&.h>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include <cmath>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for LightUtils\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
