.TH "LightUniformUploader" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightUniformUploader \- Represents the \fBLightUniformUploader\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LightUtils\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBUploadLights\fP (std::shared_ptr< \fBShaderProgram\fP > program, const std::vector< \fBLight\fP > &lights)"
.br
.RI "Uploads light data to shader uniforms\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the \fBLightUniformUploader\fP type\&. 
.SH "Member Function Documentation"
.PP 
.SS "void LightUniformUploader::UploadLights (std::shared_ptr< \fBShaderProgram\fP > program, const std::vector< \fBLight\fP > & lights)\fR [static]\fP"

.PP
Uploads light data to shader uniforms\&. 
.PP
\fBParameters\fP
.RS 4
\fIprogram\fP Value for program\&. 
.br
\fIlights\fP Value for lights\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
