.TH "src/Rendering/Lighting/LightUtils.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/LightUtils.h \- Declarations for LightUtils\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br
\fR#include 'Rendering/Shaders/ShaderProgram\&.h'\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLightUniformUploader\fP"
.br
.RI "Represents the \fBLightUniformUploader\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for LightUtils\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
