.TH "src/Rendering/Materials/MaterialDefaults.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/MaterialDefaults.cpp \- Implementation for MaterialDefaults\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'Rendering/Core/Screen\&.h'\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation for MaterialDefaults\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
