.TH "MaterialRegistryEntry" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialRegistryEntry \- Holds data for \fBMaterialRegistryEntry\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MaterialRegistry\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBid\fP"
.br
.ti -1c
.RI "std::string \fBdisplayName\fP"
.br
.ti -1c
.RI "bool \fBisBuiltIn\fP = false"
.br
.ti -1c
.RI "std::string \fBassetRef\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBMaterialRegistryEntry\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
