.TH "MaterialDefaults::ColorMaterial" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialDefaults::ColorMaterial \- Represents the \fBColorMaterial\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MaterialDefaults\&.h>\fP
.PP
Inherits \fBMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorMaterial\fP (std::shared_ptr< \fBShaderProgram\fP > program)"
.br
.RI "Constructs a new \fBColorMaterial\fP instance\&. "
.in -1c

Public Member Functions inherited from \fBMaterial\fP
.in +1c
.ti -1c
.RI "\fBMaterial\fP (std::shared_ptr< \fBShaderProgram\fP > program)"
.br
.RI "Constructs a new \fBMaterial\fP instance\&. "
.ti -1c
.RI "virtual \fB~Material\fP ()"
.br
.RI "Destroys this \fBMaterial\fP instance\&. "
.ti -1c
.RI "template<typename T> bool \fBset\fP (const std::string &name, T value)"
.br
.ti -1c
.RI "virtual void \fBbind\fP ()"
.br
.ti -1c
.RI "void \fBunbind\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBShaderProgram\fP > \fBgetShader\fP ()"
.br
.ti -1c
.RI "void \fBsetShader\fP (std::shared_ptr< \fBShaderProgram\fP > program)"
.br
.ti -1c
.RI "void \fBsetCastsShadows\fP (bool value)"
.br
.ti -1c
.RI "bool \fBcastsShadows\fP () const"
.br
.ti -1c
.RI "void \fBsetReceivesShadows\fP (bool value)"
.br
.ti -1c
.RI "bool \fBreceivesShadows\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBColorMaterial\fP > \fBCreate\fP (Math3D::Vec4 color=Color::MAGENTA)"
.br
.RI "Creates a new object\&. "
.in -1c

Static Public Member Functions inherited from \fBMaterial\fP
.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBMaterial\fP > \fBCopy\fP (std::shared_ptr< \fBMaterial\fP > material)"
.br
.ti -1c
.RI "template<typename T> static std::shared_ptr< T > \fBGetAs\fP (std::shared_ptr< \fBMaterial\fP > matPtr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ValueContainer< Math3D::Vec4 > \fBColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the \fBColorMaterial\fP type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColorMaterial::ColorMaterial (std::shared_ptr< \fBShaderProgram\fP > program)"

.PP
Constructs a new \fBColorMaterial\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIprogram\fP Value for program\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBColorMaterial\fP > ColorMaterial::Create (Math3D::Vec4 color = \fRColor::MAGENTA\fP)\fR [static]\fP"

.PP
Creates a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP Color value\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the resulting object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
