.TH "src/Rendering/Materials/MaterialRegistry.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/MaterialRegistry.h \- Declarations for \fBMaterialRegistry\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaterialRegistryEntry\fP"
.br
.RI "Holds data for \fBMaterialRegistryEntry\fP\&. "
.ti -1c
.RI "class \fBMaterialRegistry\fP"
.br
.RI "Represents the \fBMaterialRegistry\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBMaterialRegistry\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
