.TH "MaterialDefaults::FlatImageMaterial" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialDefaults::FlatImageMaterial \- Represents the \fBFlatImageMaterial\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MaterialDefaults\&.h>\fP
.PP
Inherits \fBMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlatImageMaterial\fP (std::shared_ptr< \fBShaderProgram\fP > program, std::shared_ptr< \fBTexture\fP > texture)"
.br
.RI "Constructs a new \fBFlatImageMaterial\fP instance\&. "
.ti -1c
.RI "void \fBbind\fP () override"
.br
.RI "Binds this resource\&. "
.in -1c

Public Member Functions inherited from \fBMaterial\fP
.in +1c
.ti -1c
.RI "\fBMaterial\fP (std::shared_ptr< \fBShaderProgram\fP > program)"
.br
.RI "Constructs a new \fBMaterial\fP instance\&. "
.ti -1c
.RI "virtual \fB~Material\fP ()"
.br
.RI "Destroys this \fBMaterial\fP instance\&. "
.ti -1c
.RI "template<typename T> bool \fBset\fP (const std::string &name, T value)"
.br
.ti -1c
.RI "void \fBunbind\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBShaderProgram\fP > \fBgetShader\fP ()"
.br
.ti -1c
.RI "void \fBsetShader\fP (std::shared_ptr< \fBShaderProgram\fP > program)"
.br
.ti -1c
.RI "void \fBsetCastsShadows\fP (bool value)"
.br
.ti -1c
.RI "bool \fBcastsShadows\fP () const"
.br
.ti -1c
.RI "void \fBsetReceivesShadows\fP (bool value)"
.br
.ti -1c
.RI "bool \fBreceivesShadows\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBFlatImageMaterial\fP > \fBCreate\fP (std::shared_ptr< \fBTexture\fP > tex, Math3D::Vec4 color=Color::WHITE)"
.br
.RI "Creates a new object\&. "
.in -1c

Static Public Member Functions inherited from \fBMaterial\fP
.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBMaterial\fP > \fBCopy\fP (std::shared_ptr< \fBMaterial\fP > material)"
.br
.ti -1c
.RI "template<typename T> static std::shared_ptr< T > \fBGetAs\fP (std::shared_ptr< \fBMaterial\fP > matPtr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ValueContainer< Math3D::Vec4 > \fBColor\fP"
.br
.ti -1c
.RI "ValueContainer< std::shared_ptr< \fBTexture\fP > > \fBTex\fP"
.br
.ti -1c
.RI "ValueContainer< Math3D::Vec3 > \fBViewPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the \fBFlatImageMaterial\fP type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FlatImageMaterial::FlatImageMaterial (std::shared_ptr< \fBShaderProgram\fP > program, std::shared_ptr< \fBTexture\fP > texture)"

.PP
Constructs a new \fBFlatImageMaterial\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIprogram\fP Value for program\&. 
.br
\fItexture\fP Value for texture\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void FlatImageMaterial::bind ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Binds this resource\&. 
.PP
Reimplemented from \fBMaterial\fP\&.
.SS "std::shared_ptr< \fBFlatImageMaterial\fP > FlatImageMaterial::Create (std::shared_ptr< \fBTexture\fP > tex, Math3D::Vec4 color = \fRColor::WHITE\fP)\fR [static]\fP"

.PP
Creates a new object\&. 
.PP
\fBParameters\fP
.RS 4
\fItex\fP Value for tex\&. 
.br
\fIcolor\fP Color value\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the resulting object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
