.TH "src/Rendering/Materials/MaterialDefaults.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/MaterialDefaults.h \- Declarations for MaterialDefaults\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <map>\fP
.br
\fR#include <memory>\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include 'Rendering/Shaders/ShaderProgram\&.h'\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br
\fR#include 'Foundation/Math/Color\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br
\fR#include 'Rendering/Lighting/LightUtils\&.h'\fP
.br
\fR#include 'Foundation/Util/ValueContainer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaterialDefaults::ColorMaterial\fP"
.br
.RI "Represents the \fBColorMaterial\fP type\&. "
.ti -1c
.RI "class \fBMaterialDefaults::ImageMaterial\fP"
.br
.RI "Represents the \fBImageMaterial\fP type\&. "
.ti -1c
.RI "class \fBMaterialDefaults::LitColorMaterial\fP"
.br
.RI "Represents the \fBLitColorMaterial\fP type\&. "
.ti -1c
.RI "class \fBMaterialDefaults::LitImageMaterial\fP"
.br
.RI "Represents the \fBLitImageMaterial\fP type\&. "
.ti -1c
.RI "class \fBMaterialDefaults::FlatColorMaterial\fP"
.br
.RI "Represents the \fBFlatColorMaterial\fP type\&. "
.ti -1c
.RI "class \fBMaterialDefaults::FlatImageMaterial\fP"
.br
.RI "Represents the \fBFlatImageMaterial\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for MaterialDefaults\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
