.TH "src/Rendering/Materials/MaterialRegistry.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/MaterialRegistry.cpp \- Implementation for \fBMaterialRegistry\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Materials/MaterialRegistry\&.h'\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br
\fR#include 'Foundation/IO/File\&.h'\fP
.br
\fR#include 'Assets/Descriptors/MaterialAsset\&.h'\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'Rendering/Materials/PBRMaterial\&.h'\fP
.br
\fR#include 'Foundation/Util/StringUtils\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <filesystem>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBMaterialRegistry\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
