.TH "src/Rendering/Geometry/Mesh.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/Mesh.h \- Declarations for \fBMesh\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <glad/glad\&.h>\fP
.br
\fR#include <SDL3/SDL\&.h>\fP
.br
\fR#include <SDL3/SDL_opengl\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Geometry/Drawable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.RI "Holds data for \fBVertex\fP\&. "
.ti -1c
.RI "class \fBMesh\fP"
.br
.RI "Represents the \fBMesh\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBVertexBufferObject\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBVertexArrayObject\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBElementBufferObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBMesh\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
