.TH "src/Rendering/Geometry/ModelPrefabs.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/ModelPrefabs.h \- Declarations for \fBModelPrefabs\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'Rendering/Geometry/ModelPartPrefabs\&.h'\fP
.br
\fR#include 'Rendering/Geometry/Model\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBModelPrefabs\fP"
.br
.RI "Holds data for \fBModelPrefabs\fP\&. "
.ti -1c
.RI "struct \fBModelPrefabs::CubeMaterialDefinition\fP"
.br
.RI "Holds data for \fBCubeMaterialDefinition\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBModelPrefabs\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
