.TH "ModelPrefabs::CubeMaterialDefinition" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelPrefabs::CubeMaterialDefinition \- Holds data for \fBCubeMaterialDefinition\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ModelPrefabs\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBCubeMaterialDefinition\fP > \fBCreate\fP ()"
.br
.RI "Creates a new object\&. "
.ti -1c
.RI "static std::shared_ptr< \fBCubeMaterialDefinition\fP > \fBCreateSame\fP (PMaterial mat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PMaterial \fBmatTop\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.ti -1c
.RI "PMaterial \fBmatBottom\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.ti -1c
.RI "PMaterial \fBmatLeft\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.ti -1c
.RI "PMaterial \fBmatRight\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.ti -1c
.RI "PMaterial \fBmatFront\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.ti -1c
.RI "PMaterial \fBmatBack\fP = \fBMaterialDefaults::ColorMaterial::Create\fP(Color::MAGENTA)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBCubeMaterialDefinition\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBCubeMaterialDefinition\fP > ModelPrefabs::CubeMaterialDefinition::Create ()\fR [inline]\fP, \fR [static]\fP"

.PP
Creates a new object\&. 
.PP
\fBReturns\fP
.RS 4
Pointer to the resulting object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
