.TH "src/Rendering/Geometry/ModelPart.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/ModelPart.cpp \- Implementation for \fBModelPart\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Geometry/ModelPart\&.h'\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBModelPart\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
