.TH "src/Rendering/Geometry/Model.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/Model.h \- Declarations for \fBModel\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Foundation/Util/Types\&.h'\fP
.br
\fR#include 'Rendering/Geometry/Drawable\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Geometry/ModelPart\&.h'\fP
.br
\fR#include 'Scene/Camera\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <glad/glad\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBModel\fP"
.br
.RI "Holds data for \fBModel\fP\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBModel\fP > \fBPModel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBModel\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
