.TH "src/Rendering/Geometry/ModelPart.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/ModelPart.h \- Declarations for \fBModelPart\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Rendering/Geometry/Mesh\&.h'\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Geometry/Drawable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBModelPart\fP"
.br
.RI "Holds data for \fBModelPart\fP\&. "
.ti -1c
.RI "struct \fBModelPartFactory\fP"
.br
.RI "Holds data for \fBModelPartFactory\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBModelPart\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
