.TH "src/Rendering/Geometry/ModelPartPrefabs.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Geometry/ModelPartPrefabs.h \- Declarations for \fBModelPartPrefabs\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Rendering/Geometry/ModelPart\&.h'\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBModelPartPrefabs\fP"
.br
.RI "Holds data for \fBModelPartPrefabs\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBModelPartPrefabs\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
