.TH "src/Rendering/Core/Screen.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/Screen.h \- Declarations for \fBScreen\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include 'Rendering/Core/FrameBuffer\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include 'Scene/Camera\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Shaders/ShaderProgram\&.h'\fP
.br
\fR#include 'Rendering/Geometry/ModelPartPrefabs\&.h'\fP
.br
\fR#include 'Platform/Window/RenderWindow\&.h'\fP
.br
\fR#include 'Rendering/Core/Graphics\&.h'\fP
.br
\fR#include 'Foundation/Math/Color\&.h'\fP
.br
\fR#include 'Rendering/Lighting/Environment\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScreen\fP"
.br
.RI "Represents the \fBScreen\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBView\fP > \fBPView\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBScreen\fP > \fBPScreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBScreen\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
