.TH "src/Rendering/Core/Screen.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/Screen.cpp \- Implementation for \fBScreen\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Core/Screen\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br
\fR#include 'Rendering/Core/View\&.h'\fP
.br
\fR#include <chrono>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBScreen\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
