.TH "src/Rendering/Lighting/ShadowRenderer.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/ShadowRenderer.cpp \- Implementation for \fBShadowRenderer\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Lighting/ShadowRenderer\&.h'\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <array>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <string>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include 'Rendering/Geometry/Mesh\&.h'\fP
.br
\fR#include 'Rendering/Shaders/ShaderProgram\&.h'\fP
.br
\fR#include 'Rendering/Core/Screen\&.h'\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Geometry/ModelPart\&.h'\fP
.br
\fR#include <cmath>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBShadowRenderer\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
