.TH "src/Rendering/Lighting/ShadowMap.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/ShadowMap.h \- Declarations for ShadowMap\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <glad/glad\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShadowMap2D\fP"
.br
.RI "Represents the \fBShadowMap2D\fP type\&. "
.ti -1c
.RI "class \fBShadowMapCube\fP"
.br
.RI "Represents the \fBShadowMapCube\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for ShadowMap\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
