.TH "src/Rendering/Lighting/ShadowRenderer.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Lighting/ShadowRenderer.h \- Declarations for \fBShadowRenderer\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include 'Rendering/Lighting/Light\&.h'\fP
.br
\fR#include 'Scene/Camera\&.h'\fP
.br
\fR#include 'Foundation/Math/Math3D\&.h'\fP
.br
\fR#include 'Rendering/Lighting/ShadowMap\&.h'\fP
.br
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBShadowLightData\fP"
.br
.RI "Holds data for \fBShadowLightData\fP\&. "
.ti -1c
.RI "struct \fBShadowCasterBounds\fP"
.br
.RI "Holds data for \fBShadowCasterBounds\fP\&. "
.ti -1c
.RI "class \fBShadowRenderer\fP"
.br
.RI "Represents the \fBShadowRenderer\fP type\&. "
.ti -1c
.RI "struct \fBShadowRenderer::ShadowDrawItem\fP"
.br
.RI "Holds data for \fBShadowDrawItem\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBShadowRenderer\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
