.TH "ShadowCasterBounds" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShadowCasterBounds \- Holds data for \fBShadowCasterBounds\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ShadowRenderer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Math3D::Vec3 \fBmin\fP"
.br
.ti -1c
.RI "Math3D::Vec3 \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBShadowCasterBounds\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
