.TH "SkyBox6Face" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkyBox6Face \- Holds data for \fBSkyBox6Face\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SkyBox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PAsset \fBtopFaceAsset\fP = nullptr"
.br
.ti -1c
.RI "PAsset \fBbottomFaceAsset\fP = nullptr"
.br
.ti -1c
.RI "PAsset \fBleftFaceAsset\fP = nullptr"
.br
.ti -1c
.RI "PAsset \fBrightFaceAsset\fP = nullptr"
.br
.ti -1c
.RI "PAsset \fBfrontFaceAsset\fP = nullptr"
.br
.ti -1c
.RI "PAsset \fBbackFaceAsset\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBSkyBox6Face\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
