.TH "src/Rendering/Textures/SkyBox.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Textures/SkyBox.h \- Declarations for \fBSkyBox\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Geometry/Model\&.h'\fP
.br
\fR#include 'Rendering/Materials/SkyboxMaterial\&.h'\fP
.br
\fR#include 'Rendering/Textures/CubeMap\&.h'\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br
\fR#include 'Scene/Camera\&.h'\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSkyBox6Face\fP"
.br
.RI "Holds data for \fBSkyBox6Face\fP\&. "
.ti -1c
.RI "class \fBSkyBox\fP"
.br
.RI "Represents the \fBSkyBox\fP type\&. "
.ti -1c
.RI "class \fBSkyBoxLoader\fP"
.br
.RI "Represents the \fBSkyBoxLoader\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBSkyBox\fP > \fBPSkyBox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBSkyBox\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
