.TH "src/Rendering/Materials/SkyboxMaterial.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Materials/SkyboxMaterial.h \- Declarations for \fBSkyboxMaterial\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include 'Rendering/Materials/Material\&.h'\fP
.br
\fR#include 'Rendering/Textures/CubeMap\&.h'\fP
.br
\fR#include 'Foundation/Util/ValueContainer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSkyboxMaterial\fP"
.br
.RI "Represents the \fBSkyboxMaterial\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBSkyboxMaterial\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
