.TH "SkyBoxLoader" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkyBoxLoader \- Represents the \fBSkyBoxLoader\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SkyBox\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBSkyBox\fP > \fBCreateSkyBox\fP (const std::string &directoryAssetPath, const std::string &skyboxName)"
.br
.RI "Creates sky box\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the \fBSkyBoxLoader\fP type\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBSkyBox\fP > SkyBoxLoader::CreateSkyBox (const std::string & directoryAssetPath, const std::string & skyboxName)\fR [static]\fP"

.PP
Creates sky box\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirectoryAssetPath\fP Filesystem path for directory asset path\&. 
.br
\fIskyboxName\fP Name used for skybox name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the resulting object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
