.TH "src/Rendering/Fonts/STBTrueTypeFont.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Fonts/STBTrueTypeFont.h \- Declarations for STBTrueTypeFont\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'STB/stb_truetype\&.h'\fP
.br
\fR#include 'Rendering/Fonts/Font\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTrueTypeFont\fP"
.br
.RI "Represents the \fBTrueTypeFont\fP type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations for STBTrueTypeFont\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
