.TH "src/Rendering/Fonts/STBTrueTypeFont.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Fonts/STBTrueTypeFont.cpp \- Implementation for STBTrueTypeFont\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Fonts/STBTrueTypeFont\&.h'\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include 'Rendering/Materials/MaterialDefaults\&.h'\fP
.br
\fR#include 'STB/stb_truetype\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation for STBTrueTypeFont\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
