.TH "src/Rendering/Textures/Texture.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Textures/Texture.cpp \- Implementation for \fBTexture\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Textures/Texture\&.h'\fP
.br
\fR#include 'Assets/Core/AssetDescriptorUtils\&.h'\fP
.br
\fR#include 'Foundation/Logging/Logbot\&.h'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <SDL3/SDL\&.h>\fP
.br
\fR#include 'Rendering/Core/Graphics\&.h'\fP
.br
\fR#include 'STB/stb_image\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "Logbot \fBtextureLogger\fP = Logbot::CreateInstance('Texture')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation for \fBTexture\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
