.TH "TextCacheKey" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextCacheKey \- Holds data for \fBTextCacheKey\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Font\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBTextCacheKey\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtext\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds data for \fBTextCacheKey\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
