.TH "src/Rendering/Textures/Texture.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Textures/Texture.h \- Declarations for \fBTexture\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <glad/glad\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Assets/Core/Asset\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTexture\fP"
.br
.RI "Represents the \fBTexture\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBTexture\fP > \fBPTexture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBTexture\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
