.TH "Uniform< T >" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uniform< T > \- Represents the \fBUniform\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ShaderProgram\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniform\fP ()=default"
.br
.RI "Constructs a new \fBUniform\fP instance\&. "
.ti -1c
.RI "\fBUniform\fP (const T &v)"
.br
.RI "Constructs a new \fBUniform\fP instance\&. "
.ti -1c
.RI "void \fBset\fP (const T &v)"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Uniform< T >"Represents the \fBUniform\fP type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBUniform\fP< T >::Uniform (const T & v)\fR [inline]\fP"

.PP
Constructs a new \fBUniform\fP instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP Value for v\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
