.TH "src/Rendering/Core/View.cpp" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/View.cpp \- Implementation for \fBView\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Rendering/Core/View\&.h'\fP
.br
\fR#include <glm/gtc/matrix_transform\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Implementation for \fBView\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
