.TH "src/Rendering/Core/View.h" 3 "Render Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rendering/Core/View.h \- Declarations for \fBView\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Rendering/Core/Screen\&.h'\fP
.br
\fR#include 'Platform/Window/RenderWindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBView\fP"
.br
.RI "Represents the \fBView\fP type\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBView\fP > \fBPView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declarations for \fBView\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Render Engine from the source code\&.
