CubeMap
GLuint CubeMap::textureID
int CubeMap::size
bool CubeMap::ownsTexture
CubeMap::CubeMap()=default
Constructs a new CubeMap instance.
Referenced by CubeMap, CubeMap, operator=, operator=.
CubeMap::~CubeMap()
Destroys this CubeMap instance.
References dispose.
CubeMap::CubeMap(const CubeMap &)=delete
Constructs a new CubeMap instance.
References CubeMap.
CubeMap & CubeMap::operator=(const CubeMap &)=delete
Assigns from another instance.
References CubeMap.
CubeMap::CubeMap(CubeMap &&other) noexcept
Constructs a new CubeMap instance.
other Value for other.
References CubeMap.
CubeMap & CubeMap::operator=(CubeMap &&other) noexcept
Assigns from another instance.
other Value for other.
References CubeMap, dispose.
void CubeMap::bind(unsigned int slot=0) const
Binds this resource.
slot Value for slot.
void CubeMap::unbind() const
Unbinds this resource.
void CubeMap::dispose()
Disposes this object.
Referenced by operator=, ~CubeMap.
int CubeMap::getSize() const
Returns the size.
Computed numeric result.
GLuint CubeMap::getID() const
std::shared_ptr< CubeMap > CubeMap::Load(PAsset posX, PAsset negX, PAsset posY, PAsset negY, PAsset posZ, PAsset negZ)