ShadowMapCube
GLuint ShadowMapCube::fbo
GLuint ShadowMapCube::depthCube
int ShadowMapCube::size
void ShadowMapCube::init()
Initializes this object.
ShadowMapCube::ShadowMapCube()=default
Constructs a new ShadowMapCube instance.
Referenced by operator=, operator=, ShadowMapCube, ShadowMapCube.
ShadowMapCube::ShadowMapCube(int size)
Constructs a new ShadowMapCube instance.
size Number of elements or bytes. Result of this operation.
ShadowMapCube::~ShadowMapCube()
Destroys this ShadowMapCube instance.
ShadowMapCube::ShadowMapCube(const ShadowMapCube &)=delete
Constructs a new ShadowMapCube instance.
References ShadowMapCube.
ShadowMapCube & ShadowMapCube::operator=(const ShadowMapCube &)=delete
Assigns from another instance.
References ShadowMapCube.
ShadowMapCube::ShadowMapCube(ShadowMapCube &&other) noexcept
Constructs a new ShadowMapCube instance.
other Value for other.
References ShadowMapCube.
ShadowMapCube & ShadowMapCube::operator=(ShadowMapCube &&other) noexcept
Assigns from another instance.
other Value for other.
References ShadowMapCube.
void ShadowMapCube::resize(int newSize)
Resizes internal resources.
newSize Number of elements or bytes.
void ShadowMapCube::bindFace(GLenum face) const
Binds face.
face Value for face.
void ShadowMapCube::unbind() const
Unbinds this resource.
void ShadowMapCube::clear() const
Clears the current state.
GLuint ShadowMapCube::getDepthTexture() const
Returns the depth texture.
Result of this operation.
int ShadowMapCube::getSize() const