LightUniformUploader
void LightUniformUploader::UploadLights(std::shared_ptr< ShaderProgram > program, const std::vector< Light > &lights)
Uploads light data to shader uniforms.
program Value for program. lights Value for lights.
References ShadowRenderer::GetFrameId, ShadowRenderer::GetShadowDataForLight.
Referenced by MaterialDefaults::FlatColorMaterial::bind, MaterialDefaults::FlatImageMaterial::bind, MaterialDefaults::LitColorMaterial::bind, MaterialDefaults::LitImageMaterial::bind, PBRMaterial::bind.