Graphics2D
BatchMode2D
GraphicsContext Graphics2D::context
PScreen Graphics2D::target
PCamera Graphics2D::uiCamera
std::shared_ptr<ModelPart> Graphics2D::unitQuad
std::shared_ptr<ModelPart> Graphics2D::unitCircle
PMaterial Graphics2D::colorMaterial
PMaterial Graphics2D::imageMaterial
std::shared_ptr<ModelPart> Graphics2D::batchPart
PMaterial Graphics2D::batchMaterial
std::vector<Vertex> Graphics2D::batchVertices
std::vector<uint32_t> Graphics2D::batchIndices
BatchMode2D Graphics2D::batchMode
PTexture Graphics2D::batchTexture
size_t Graphics2D::maxBatchQuads
std::vector<PFont> Graphics2D::queuedFonts
void Graphics2D::drawMesh(std::shared_ptr< ModelPart > part, const Math3D::Mat4 &modelMatrix, PTexture tex=nullptr)
void Graphics2D::ensureBatchResources()
Ensures batch resources.
void Graphics2D::resetBatch()
Resets batch.
void Graphics2D::flushBatch()
Flushes queued 2D draw batches.
void Graphics2D::queueFontForFlush(PFont font)
Queues a font for end-of-frame flush.
font Value for font.
void Graphics2D::flushQueuedFonts()
Flushes queued font draw calls.
void Graphics2D::beginBatch(BatchMode2D mode, PTexture texture=nullptr)
Begins batch.
mode Mode or type selector. texture Value for texture.
void Graphics2D::submitQuad(const Math3D::Vec3 &p0, const Math3D::Vec3 &p1, const Math3D::Vec3 &p2, const Math3D::Vec3 &p3, const Math3D::Vec2 &uv0, const Math3D::Vec2 &uv1, const Math3D::Vec2 &uv2, const Math3D::Vec2 &uv3, const Math3D::Vec4 &color, BatchMode2D mode, PTexture texture=nullptr)
Submits a quad to the active batch.
p0 Value for p 0. p1 Value for p 1. p2 Value for p 2. p3 Value for p 3. uv0 Value for uv 0. uv1 Value for uv 1. uv2 Value for uv 2. uv3 Value for uv 3. color Color value. mode Mode or type selector. texture Value for texture.
Graphics2D::Graphics2D(PScreen screenContext)
Constructs a new Graphics2D instance.
screenContext Value for screen context.
References Vertex::Build, MaterialDefaults::ColorMaterial::Create, MaterialDefaults::ImageMaterial::Create, ModelPartFactory::Create, ModelPartPrefabs::MakeCirclePlane.
Referenced by DrawEllipse, DrawImage, DrawLine, DrawRect, DrawString, FillEllipse, FillRect, FillTriangle, SetBackgroundColor, SetFont, SetFontSize, SetStrokeWidth.
void Graphics2D::resize(int w, int h)
void Graphics2D::begin()
Begins a 2D drawing batch.
void Graphics2D::end()
Ends the current 2D drawing batch.
GraphicsContext & Graphics2D::getContext()
Returns the context.
Reference to the resulting value.
void Graphics2D::SetForegroundColor(Graphics2D &graphics, const Color &foregroundColor=Color::WHITE)
void Graphics2D::SetBackgroundColor(Graphics2D &graphics, const Color &backgroundColor=Color::BLACK)
Sets the background color.
graphics Value for graphics. backgroundColor Color value.
References Graphics2D.
void Graphics2D::SetStrokeWidth(Graphics2D &graphics, float width=1.0f)
Sets the stroke width.
graphics Value for graphics. width Dimension value.
References Graphics2D.
void Graphics2D::SetFontSize(Graphics2D &graphics, float size=1.0f)
Sets the font size.
graphics Value for graphics. size Number of elements or bytes.
References Graphics2D.
void Graphics2D::SetFont(Graphics2D &graphics, PFont font)
Sets the font.
graphics Value for graphics. font Value for font.
References Graphics2D.
void Graphics2D::DrawLine(Graphics2D &graphics, float x1, float y1, float x2, float y2)
Draws line.
graphics Value for graphics. x1 Value for x 1. y1 Value for y 1. x2 Value for x 2. y2 Value for y 2.
References Graphics2D.
Referenced by DrawEllipse, DrawRect.
void Graphics2D::DrawRect(Graphics2D &graphics, float x, float y, float w, float h)
Draws rect.
graphics Value for graphics. x Spatial value used by this operation. y Spatial value used by this operation. w Value for w. h Value for h.
References DrawLine, Graphics2D.
void Graphics2D::FillRect(Graphics2D &graphics, float x, float y, float w, float h)
Fills a rectangle.
graphics Value for graphics. x Spatial value used by this operation. y Spatial value used by this operation. w Value for w. h Value for h.
References Graphics2D.
void Graphics2D::FillTriangle(Graphics2D &graphics, float x1, float y1, float x2, float y2, float x3, float y3)
Fills a triangle.
graphics Value for graphics. x1 Value for x 1. y1 Value for y 1. x2 Value for x 2. y2 Value for y 2. x3 Value for x 3. y3 Value for y 3.
References Graphics2D.
void Graphics2D::DrawEllipse(Graphics2D &graphics, float x, float y, float w, float h)
Draws ellipse.
graphics Value for graphics. x Spatial value used by this operation. y Spatial value used by this operation. w Value for w. h Value for h.
References DrawLine, Graphics2D.
void Graphics2D::FillEllipse(Graphics2D &graphics, float x, float y, float w, float h)
Fills an ellipse.
graphics Value for graphics. x Spatial value used by this operation. y Spatial value used by this operation. w Value for w. h Value for h.
References Graphics2D.
void Graphics2D::DrawImage(Graphics2D &graphics, PTexture tex, float x, float y, float w=-1, float h=-1)
Draws image.
graphics Value for graphics. tex Value for tex. x Spatial value used by this operation. y Spatial value used by this operation. w Value for w. h Value for h.
References Graphics2D.
void Graphics2D::DrawString(Graphics2D &graphics, std::string text, float x, float y, bool useCache=true)
Draws string.
graphics Value for graphics. text Value for text. x Spatial value used by this operation. y Spatial value used by this operation. useCache Flag controlling use cache.
References Graphics2D.