ShadowRenderer
void ShadowRenderer::BeginFrame(PCamera camera, const std::vector< ShadowCasterBounds > *casters=nullptr)
Begins frame.
camera Value for camera. casters Value for casters.
void ShadowRenderer::RenderShadows(const std::shared_ptr< Mesh > &mesh, const Math3D::Mat4 &model, const std::shared_ptr< Material > &material)
Renders shadows.
mesh Value for mesh. model Mode or type selector. material Value for material.
Referenced by Model::drawShadows.
void ShadowRenderer::RenderShadowsBatch(const std::vector< ShadowDrawItem > &items)
Renders shadows batch.
items Value for items.
void ShadowRenderer::BindShadowSamplers(const std::shared_ptr< ShaderProgram > &program)
Binds shadow samplers.
program Value for program.
Referenced by MaterialDefaults::FlatColorMaterial::bind, MaterialDefaults::FlatImageMaterial::bind, MaterialDefaults::LitColorMaterial::bind, MaterialDefaults::LitImageMaterial::bind, PBRMaterial::bind.
void ShadowRenderer::GetShadowDataForLight(size_t index, const Light &light, ShadowLightData &outData)
Returns the shadow data for light.
index Identifier or index value. light Value for light. outData Buffer that receives data data.
Referenced by LightUniformUploader::UploadLights.
uint64_t ShadowRenderer::GetFrameId()
Returns the frame id.
Result of this operation.
Referenced by LightUniformUploader::UploadLights.
bool ShadowRenderer::IsEnabled()
Checks whether enabled.
True when the condition is satisfied; otherwise false.
std::shared_ptr< Texture > ShadowRenderer::GetDepthBuffer()
Returns the depth buffer.
Pointer to the resulting object.
void ShadowRenderer::SetDebugShadows(bool enabled)
Sets the debug shadows.
enabled Flag controlling enabled.
bool ShadowRenderer::GetDebugShadows()
Returns the debug shadows.
True when the operation succeeds; otherwise false.
void ShadowRenderer::CycleDebugShadows()
Cycles the active debug shadow visualization mode.
int ShadowRenderer::GetDebugShadowsMode()
Returns the debug shadows mode.
Computed numeric result.
void ShadowRenderer::SetDebugShadowsMode(int mode)
Sets the debug shadows mode.
mode Mode or type selector.
void ShadowRenderer::SetGlobalDebugOverrideEnabled(bool enabled)
Sets the global debug override enabled.
enabled Flag controlling enabled.
bool ShadowRenderer::GetGlobalDebugOverrideEnabled()
Returns the global debug override enabled.
True when the operation succeeds; otherwise false.
void ShadowRenderer::SetGlobalDebugOverrideMode(int mode)
Sets the global debug override mode.
mode Mode or type selector.
int ShadowRenderer::GetGlobalDebugOverrideMode()
Returns the global debug override mode.
Computed numeric result.
void ShadowRenderer::SetSelectedLightIndex(int index)
Sets the selected light index.
index Identifier or index value.
int ShadowRenderer::GetSelectedLightIndex()
Returns the selected light index.
Computed numeric result.
void ShadowRenderer::SetDirectionalCascadeKernelMarginTexels(float value)
Sets the directional cascade kernel margin texels.
value Value for value.
float ShadowRenderer::GetDirectionalCascadeKernelMarginTexels()
Returns the directional cascade kernel margin texels.
Computed numeric result.
void ShadowRenderer::SetShadowReceiverNormalBlend(float value)
Sets the shadow receiver normal blend.
value Value for value.
float ShadowRenderer::GetShadowReceiverNormalBlend()
Returns the shadow receiver normal blend.
Computed numeric result.
void ShadowRenderer::SetDebugLogging(bool enabled)
Sets the debug logging.
enabled Flag controlling enabled.
bool ShadowRenderer::GetDebugLogging()
Returns the debug logging.
True when the operation succeeds; otherwise false.
void ShadowRenderer::ensureShadowPrograms()
Ensures shadow programs.
Math3D::Mat4 ShadowRenderer::computeDirectionalMatrix(const Light &light, PCamera camera)
Computes directional matrix.
light Value for light. camera Value for camera. Result of this operation.
Math3D::Mat4 ShadowRenderer::computeSpotMatrix(const Light &light)
Computes spot matrix.
light Value for light. Result of this operation.
void ShadowRenderer::computePointMatrices(const Light &light, std::vector< Math3D::Mat4 > &outMatrices)
Computes point matrices.
light Value for light. outMatrices Output value for matrices.