ShaderProgram
ShaderBundle ShaderProgram::sh_vert
ShaderBundle ShaderProgram::sh_frag
ShaderBundle ShaderProgram::sh_geom
ShaderBundle ShaderProgram::sh_tess
ShaderBundle ShaderProgram::sh_comp
ShaderBundle ShaderProgram::sh_task
ShaderBundle ShaderProgram::sh_srtx
Shader ShaderProgram::programHandle
std::string ShaderProgram::shaderLog
std::unordered_map<std::string, GLint> ShaderProgram::uniformLocationCache
GLint ShaderProgram::getUniformLocationCached(const std::string &name)
Returns a cached uniform location, querying OpenGL if needed.
name Uniform name. Uniform location, or -1 when missing.
std::string ShaderProgram::_generateShaderLog(Shader shader)
Builds a compile log string for a shader object.
shader Shader handle. Shader compile log text.
std::string ShaderProgram::_generateProgramLog(Program shader)
Builds a link log string for a program object.
shader Program handle. Program link log text.
Shader ShaderProgram::_createShader(std::string glsl, ShaderType type)
Creates shader.
glsl GLSL source code. type Shader stage type. Shader handle, or 0 on failure.
std::vector< ShaderBundle > ShaderProgram::_getShaderBundles()
Returns all stage bundles as a flat list.
Shader bundle list.
void ShaderProgram::setVertexShader(std::string glsl)
Sets the vertex shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setFragmentShader(std::string glsl)
Sets the fragment shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setGeometryShader(std::string glsl)
Sets the geometry shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setTesselationShader(std::string glsl)
Sets the tesselation shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setComputeShader(std::string glsl)
Sets the compute shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setTaskShader(std::string glsl)
Sets the task shader.
glsl GLSL source code.
References ShaderBundle::Create.
void ShaderProgram::setRTXShader(std::string glsl)
Sets the rtx shader.
glsl GLSL source code.
References ShaderBundle::Create.
ShaderBundle & ShaderProgram::getVertexShader()
Returns the vertex shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getFragmentShader()
Returns the fragment shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getGeometryShader()
Returns the geometry shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getTesselationShader()
Returns the tesselation shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getComputeShader()
Returns the compute shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getTaskShader()
Returns the task shader.
Reference to the resulting value.
ShaderBundle & ShaderProgram::getRTXShader()
Returns the rtx shader.
Reference to the resulting value.
std::string ShaderProgram::getLog()
Returns the last compile/link log message.
Log message text.
Shader ShaderProgram::compile()
Compiles and links all configured shader stages.
Program handle, or 0 on failure.
void ShaderProgram::bind()
Binds this resource.
Referenced by setUniform.
void ShaderProgram::unbind()
Unbinds this resource.
void ShaderProgram::setUniform(const std::string &name, const Uniform< T > &uniform)
Sets the uniform.
name Uniform name. uniform Uniform wrapper containing the value.
References bind.
Referenced by MaterialProperty< T >::apply.
void ShaderProgram::setUniformFast(const std::string &name, const Uniform< T > &uniform)
Sets the uniform fast.
name Uniform name. uniform Uniform wrapper containing the value.
Referenced by MaterialProperty< T >::apply.
Shader ShaderProgram::getID()
Returns the OpenGL program id.
Program handle.
ShaderProgram::~ShaderProgram()
Destroys this ShaderProgram instance.
Shader ShaderProgram::GetCurrentShaderProgram()
Returns the currently bound OpenGL program id.
Active program handle.