Material
std::shared_ptr<ShaderProgram> Material::programObjPtr
std::unordered_map<std::string, std::shared_ptr<IMaterialProperty> > Material::properties
bool Material::castsShadowsFlag
bool Material::receivesShadowsFlag
Material::Material(std::shared_ptr< ShaderProgram > program)
Constructs a new Material instance.
program Value for program.
Referenced by MaterialDefaults::ColorMaterial::ColorMaterial, ConstructedMaterial::ConstructedMaterial, MaterialDefaults::FlatColorMaterial::FlatColorMaterial, MaterialDefaults::FlatImageMaterial::FlatImageMaterial, MaterialDefaults::ImageMaterial::ImageMaterial, MaterialDefaults::LitColorMaterial::LitColorMaterial, MaterialDefaults::LitImageMaterial::LitImageMaterial, PBRMaterial::PBRMaterial, SkyboxMaterial::SkyboxMaterial.
virtual Material::~Material()
Destroys this Material instance.
bool Material::set(const std::string &name, T value)
virtual void Material::bind()
void Material::unbind()
std::shared_ptr< ShaderProgram > Material::getShader()
void Material::setShader(std::shared_ptr< ShaderProgram > program)
void Material::setCastsShadows(bool value)
bool Material::castsShadows() const
void Material::setReceivesShadows(bool value)
bool Material::receivesShadows() const
static std::shared_ptr< Material > Material::Copy(std::shared_ptr< Material > material)
static std::shared_ptr< T > Material::GetAs(std::shared_ptr< Material > matPtr)