MaterialDefaults::ColorMaterial
ValueContainer<Math3D::Vec4> MaterialDefaults::ColorMaterial::Color
ColorMaterial::ColorMaterial(std::shared_ptr< ShaderProgram > program)
Constructs a new ColorMaterial instance.
program Value for program.
References Material::Material.
std::shared_ptr< ColorMaterial > ColorMaterial::Create(Math3D::Vec4 color=Color::MAGENTA)
Creates a new object.
color Color value. Pointer to the resulting object.
Referenced by Graphics2D::Graphics2D, ModelPartPrefabs::MakeBox, ModelPartPrefabs::MakeCirclePlane, ModelPartPrefabs::MakePlane, ModelPartPrefabs::MakeSphere.