ShadowMap2D
GLuint ShadowMap2D::fbo
GLuint ShadowMap2D::depthTex
int ShadowMap2D::size
void ShadowMap2D::init()
Initializes this object.
ShadowMap2D::ShadowMap2D()=default
Constructs a new ShadowMap2D instance.
Referenced by operator=, operator=, ShadowMap2D, ShadowMap2D.
ShadowMap2D::ShadowMap2D(int size)
Constructs a new ShadowMap2D instance.
size Number of elements or bytes. Result of this operation.
ShadowMap2D::~ShadowMap2D()
Destroys this ShadowMap2D instance.
ShadowMap2D::ShadowMap2D(const ShadowMap2D &)=delete
Constructs a new ShadowMap2D instance.
References ShadowMap2D.
ShadowMap2D & ShadowMap2D::operator=(const ShadowMap2D &)=delete
Assigns from another instance.
References ShadowMap2D.
ShadowMap2D::ShadowMap2D(ShadowMap2D &&other) noexcept
Constructs a new ShadowMap2D instance.
other Value for other.
References ShadowMap2D.
ShadowMap2D & ShadowMap2D::operator=(ShadowMap2D &&other) noexcept
Assigns from another instance.
other Value for other.
References ShadowMap2D.
void ShadowMap2D::resize(int newSize)
Resizes internal resources.
newSize Number of elements or bytes.
void ShadowMap2D::bind() const
Binds this resource.
void ShadowMap2D::unbind() const
Unbinds this resource.
void ShadowMap2D::clear() const
Clears the current state.
GLuint ShadowMap2D::getDepthTexture() const
Returns the depth texture.
Result of this operation.
int ShadowMap2D::getSize() const