ShaderBundle
Shader ShaderBundle::shaderHandle
std::string ShaderBundle::shader_code
ShaderType ShaderBundle::type
bool ShaderBundle::valid
static ShaderBundle ShaderBundle::Create(std::string &glsl)
Creates a new object.
glsl Shader source code. Initialized shader bundle.
Referenced by ShaderProgram::setComputeShader, ShaderProgram::setFragmentShader, ShaderProgram::setGeometryShader, ShaderProgram::setRTXShader, ShaderProgram::setTaskShader, ShaderProgram::setTesselationShader, ShaderProgram::setVertexShader.
ShaderBundle::~ShaderBundle()
Destroys this ShaderBundle instance.