Vertex
Math3D::Vec3 Vertex::Position
Math3D::Vec3 Vertex::Normal
Math3D::Vec2 Vertex::TexCoords
Math3D::Vec4 Vertex::Color
const int Vertex::VERTEX_DATA_WIDTH
Vertex & Vertex::Pos(const Math3D::Vec3 &pos)
Sets vertex position.
pos Value for pos. Reference to the resulting value.
Referenced by Pos.
Vertex & Vertex::Pos(float x=0, float y=0, float z=0)
Sets vertex position.
x Spatial value used by this operation. y Spatial value used by this operation. z Spatial value used by this operation. Reference to the resulting value.
References Pos.
Vertex & Vertex::Norm(const Math3D::Vec3 &nml)
Sets vertex normal.
nml Value for nml. Reference to the resulting value.
Referenced by ModelPartPrefabs::MakeSphere, Norm.
Vertex & Vertex::Norm(float x=0, float y=0, float z=0)
Sets vertex normal.
x Spatial value used by this operation. y Spatial value used by this operation. z Spatial value used by this operation. Reference to the resulting value.
References Norm.
Vertex & Vertex::UV(const Math3D::Vec2 &pos)
Sets vertex UV coordinates.
pos Value for pos. Reference to the resulting value.
Referenced by ModelPartPrefabs::MakeSphere, UV.
Vertex & Vertex::UV(float u=0, float v=0)
Sets vertex UV coordinates.
u Value for u. v Value for v. Reference to the resulting value.
References UV.
Vertex & Vertex::Col(const Math3D::Vec4 &col)
Sets vertex color.
col Value for col. Reference to the resulting value.
Referenced by Col.
Vertex & Vertex::Col(float r=0, float g=0, float b=0, float a=1)
Sets vertex color.
r Value for r. g Value for g. b Value for b. a Value for a. Reference to the resulting value.
References Col.
bool Vertex::operator==(const Vertex &vtx) const
bool Vertex::operator!=(const Vertex &vtx) const
static Vertex Vertex::Build(Math3D::Vec3 pos=Math3D::Vec3::zero(), Math3D::Vec4 color=Math3D::Vec4(1, 1, 1, 1), Math3D::Vec3 normal=Math3D::Vec3::zero(), Math3D::Vec2 texcords=Math3D::Vec2(0, 0))
Builds the target output.
pos Value for pos. color Color value. normal Value for normal. texcords Value for texcords. Result of this operation.
Referenced by Graphics2D::Graphics2D, ModelPartPrefabs::MakeBox, ModelPartPrefabs::MakeCirclePlane, ModelPartPrefabs::MakePlane, ModelPartPrefabs::MakeSphere.
static Vertex Vertex::Compose(std::vector< float > &floats, int dataSize=VERTEX_DATA_WIDTH)
Composes a vertex from components.
floats Value for floats. dataSize Number of elements or bytes. Result of this operation.
static std::vector< float > Vertex::Decompose(Vertex &v)
Decomposes a vertex into scalar components.
v Value for v. Computed numeric result.