ModelPartPrefabs
static std::shared_ptr< ModelPart > ModelPartPrefabs::MakePlane(float width, float height, PMaterial mat=MaterialDefaults::ColorMaterial::Create(Color::RED), Math3D::Vec3 normal=Math3D::Vec3(0, 1, 0))
Creates plane.
width Dimension value. height Dimension value. mat Value for mat. normal Value for normal. Pointer to the resulting object.
References Vertex::Build, MaterialDefaults::ColorMaterial::Create, ModelPartFactory::Create.
Referenced by ModelPrefabs::MakeCube.
static std::shared_ptr< ModelPart > ModelPartPrefabs::MakeBox(float width, float height, float depth, PMaterial mat=MaterialDefaults::ColorMaterial::Create(Color::RED))
Creates box.
width Dimension value. height Dimension value. depth Value for depth. mat Value for mat. Pointer to the resulting object.
References Vertex::Build, MaterialDefaults::ColorMaterial::Create, ModelPartFactory::Create.
Referenced by SkyBox::SkyBox.
static std::shared_ptr< ModelPart > ModelPartPrefabs::MakeCirclePlane(float radius, int segments=32, PMaterial material=MaterialDefaults::ColorMaterial::Create(Color::RED), Math3D::Vec3 normal=Math3D::Vec3(0, 1, 0))
Creates circle plane.
radius Value for radius. segments Value for segments. material Value for material. normal Value for normal. Pointer to the resulting object.
References Vertex::Build, MaterialDefaults::ColorMaterial::Create, ModelPartFactory::Create.
Referenced by Graphics2D::Graphics2D.
static std::shared_ptr< ModelPart > ModelPartPrefabs::MakeSphere(float radius=1.0f, int slices=32, int stacks=18, PMaterial material=MaterialDefaults::ColorMaterial::Create(Color::WHITE))
Creates sphere.
radius Value for radius. slices Value for slices. stacks Value for stacks. material Value for material. Pointer to the resulting object.
References Vertex::Build, MaterialDefaults::ColorMaterial::Create, ModelPartFactory::Create, Vertex::Norm, Vertex::UV.