ModelPartFactory
std::shared_ptr<Mesh> ModelPartFactory::meshInstancePtr
std::shared_ptr<Material> ModelPartFactory::materialInstancePtr
std::vector<Vertex> ModelPartFactory::vertexCache
std::vector<uint32_t> ModelPartFactory::faceCache
ModelPartFactory::ModelPartFactory()=default
Constructs a new ModelPartFactory instance.
References ModelPartFactory.
Referenced by addVertex, Create, defineFace, ModelPartFactory.
ModelPartFactory & ModelPartFactory::addVertex(Vertex vtx, int *index=nullptr)
Adds vertex.
vtx Value for vtx. index Identifier or index value. Reference to the resulting value.
References ModelPartFactory.
ModelPartFactory & ModelPartFactory::defineFace(int vtx1, int vtx2, int vtx3, int vtx4=-1)
Adds a face definition to the model part.
vtx1 Value for vtx 1. vtx2 Value for vtx 2. vtx3 Value for vtx 3. vtx4 Value for vtx 4. Reference to the resulting value.
References ModelPartFactory.
std::shared_ptr< ModelPart > ModelPartFactory::assemble()
Builds a model part from accumulated data.
Pointer to the resulting object.
ModelPartFactory ModelPartFactory::Create(std::shared_ptr< Material > material)
Creates a new object.
material Value for material. Result of this operation.
References ModelPartFactory.
Referenced by Graphics2D::Graphics2D, ModelPartPrefabs::MakeBox, ModelPartPrefabs::MakeCirclePlane, ModelPartPrefabs::MakePlane, ModelPartPrefabs::MakeSphere.