FrameBuffer
FrameBufferObject FrameBuffer::fboID
int FrameBuffer::width
int FrameBuffer::height
PTexture FrameBuffer::texturePtr
PTexture FrameBuffer::depthTexture
std::vector<GBufferAttachment> FrameBuffer::gbufferAttachments
FrameBuffer::FrameBuffer(int width, int height)
Constructs a new FrameBuffer instance.
width Dimension value. height Dimension value.
References bind, unbind.
FrameBuffer::~FrameBuffer()
Destroys this FrameBuffer instance.
void FrameBuffer::bind()
Binds this resource.
Referenced by attachTexture, FrameBuffer, validate.
void FrameBuffer::unbind()
Unbinds this resource.
Referenced by attachTexture, FrameBuffer, validate.
void FrameBuffer::resize(int width, int height)
Resizes internal resources.
width Dimension value. height Dimension value.
void FrameBuffer::attachTexture(PTexture tex)
Attaches a texture to the framebuffer.
tex Value for tex.
References bind, unbind.
bool FrameBuffer::validate()
Checks whether validate.
True when the operation succeeds; otherwise false.
References bind, unbind.
void FrameBuffer::clear(Color clearColor=Color::BLACK)
Clears the current state.
clearColor Color value.
PTexture FrameBuffer::getTexture()
Returns the texture.
Result of this operation.
PTexture FrameBuffer::getDepthTexture()
Returns the depth texture.
Result of this operation.
PTexture FrameBuffer::getGBufferTexture(size_t index) const
Returns the g buffer texture.
index Identifier or index value. Result of this operation.
size_t FrameBuffer::getGBufferCount() const
Returns the g buffer count.
Computed numeric result.
FrameBufferObject FrameBuffer::getID() const
Returns the id.
Result of this operation.
int FrameBuffer::getWidth() const
int FrameBuffer::getHeight() const
static std::shared_ptr< FrameBuffer > FrameBuffer::Create(int width, int height)
Creates a new object.
width Dimension value. height Dimension value. Pointer to the resulting object.
Referenced by TrippleBuffer::TrippleBuffer.
static std::shared_ptr< FrameBuffer > FrameBuffer::CreateGBuffer(int width, int height)
Creates g buffer.
width Dimension value. height Dimension value. Pointer to the resulting object.