Model
Math3D::Transform Model::modelTransform
std::vector<std::shared_ptr<ModelPart> > Model::modelParts
bool Model::enableBackfaceCulling
std::string Model::sourceAssetRef
bool Model::sourceForceSmoothNormals
Model::Model()=default
Constructs a new Model instance.
Referenced by addPart.
Model & Model::addPart(std::shared_ptr< ModelPart > part)
Adds part.
part Value for part. Reference to the resulting value.
References Model.
const std::vector< std::shared_ptr< ModelPart > > & Model::getParts() const
Returns the parts.
Reference to the resulting value.
Math3D::Transform & Model::transform()
Returns the transform value.
Reference to the resulting value.
Referenced by draw, drawShadows.
void Model::setBackfaceCulling(bool enabled)
Sets the backface culling.
enabled Flag controlling enabled.
bool Model::isBackfaceCullingEnabled() const
Checks whether backface culling enabled.
True when the condition is satisfied; otherwise false.
void Model::setSourceAssetRef(const std::string &sourceRef)
Sets the source asset ref.
sourceRef Reference to source.
const std::string & Model::getSourceAssetRef() const
Returns the source asset ref.
Resulting string value.
void Model::setSourceForceSmoothNormals(bool enabled)
Sets the source force smooth normals.
enabled Flag controlling enabled.
bool Model::getSourceForceSmoothNormals() const
Returns the source force smooth normals.
True when the operation succeeds; otherwise false.
void Model::draw(const Math3D::Mat4 &parent=Math3D::Mat4(), const Math3D::Mat4 &view=Math3D::Mat4(), const Math3D::Mat4 &projection=Math3D::Mat4()) override
Draws this object.
parent Value for parent. view Value for view. projection Value for projection.
References transform.
Referenced by draw.
void Model::drawShadows(const Math3D::Mat4 &parent=Math3D::Mat4())
Draws shadows.
parent Value for parent.
References ShadowRenderer::RenderShadows, transform.
void Model::draw(PCamera cam, Nullable< Math3D::Transform > parentTransform=nullptr)
Draws this object.
cam Value for cam. parentTransform Spatial value used by this operation.
References draw.
static std::shared_ptr< Model > Model::Create()
Creates a new object.
Pointer to the resulting object.
Referenced by ModelPrefabs::MakeCube, SkyBox::SkyBox.