TrippleBuffer
FrameBufferChain TrippleBuffer::chain
int TrippleBuffer::width
int TrippleBuffer::height
TrippleBuffer::TrippleBuffer()=delete
Constructs a new TrippleBuffer instance.
TrippleBuffer::TrippleBuffer(int width, int height)
Constructs a new TrippleBuffer instance.
width Dimension value. height Dimension value.
References FrameBuffer::Create.
std::shared_ptr< FrameBuffer > TrippleBuffer::getFront()
Returns the front.
Pointer to the resulting object.
Referenced by swapBuffers.
std::shared_ptr< FrameBuffer > TrippleBuffer::getMiddle()
Returns the middle.
Pointer to the resulting object.
Referenced by getEditBuffer, swapBuffers.
std::shared_ptr< FrameBuffer > TrippleBuffer::getBack()
Returns the back.
Pointer to the resulting object.
Referenced by getDrawBuffer, swapBuffers.
std::shared_ptr< FrameBuffer > TrippleBuffer::getDisplayBuffer()
std::shared_ptr< FrameBuffer > TrippleBuffer::getEditBuffer()
Returns the edit buffer.
Pointer to the resulting object.
References getMiddle.
std::shared_ptr< FrameBuffer > TrippleBuffer::getDrawBuffer()
Returns the draw buffer.
Pointer to the resulting object.
References getBack.
void TrippleBuffer::setFront(std::shared_ptr< FrameBuffer > framePtr)
void TrippleBuffer::setMiddle(std::shared_ptr< FrameBuffer > framePtr)
Sets the middle.
framePtr Pointer to frame.
Referenced by swapBuffers.
void TrippleBuffer::setBack(std::shared_ptr< FrameBuffer > framePtr)
Sets the back.
framePtr Pointer to frame.
Referenced by swapBuffers.
void TrippleBuffer::swapBuffers()
Swaps buffers.
References getBack, getFront, getMiddle, setBack, setMiddle.
void TrippleBuffer::resizeBuffers(int width, int height)
Resizes backing GPU buffers.
width Dimension value. height Dimension value.